development:
  mem_limit: 128M
  enable_star: 1
  min_infix_len: 2
  morphology: stem_ru
  mysql41: 9312


production:
  quiet_deltas: true
  mem_limit: 128M
  enable_star: 1
  min_infix_len: 2
  morphology: stem_ru
  mysql41: 9406
  bin_path: '/usr/bin'
  searchd_binary_name: '/usr/bin/searchd'
  indexer_binary_name: '/usr/bin/indexer'